#!/bin/bash

SCRIPTSDIR=$HOME/.config/hypr/scripts

# Kill already running process
# _ps=(gammastep waybar mako)
# _ps=(waybar mako)
_ps=(mako)
for _prs in "${_ps[@]}"; do
	if [[ $(pidof ${_prs}) ]]; then
		killall -9 ${_prs}
	fi
done

# Gammastep
# gammastep &

# Apply themes
# ${SCRIPTSDIR}/gtkthemes &

# Lauch notification daemon (mako)
# ${SCRIPTSDIR}/notifications &

# Lauch statusbar (waybar)
# ${SCRIPTSDIR}/statusbar &

# Xauthority
# ${SCRIPTSDIR}/xauthority &

# dex $HOME/.config/autostart/arcolinux-welcome-app.desktop &

#insync start &
#dropbox &
#telegram-desktop &
#discord &
#nm-applet --indicator
#variety &
